# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Forgot(object):
    def setupUi(self, Forgot):
        Forgot.setObjectName("Forgot")
        Forgot.resize(346, 506)
        self.centralwidget = QtWidgets.QWidget(Forgot)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input_fields_frame = QtWidgets.QFrame(self.centralwidget)
        self.input_fields_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.input_fields_frame.setMaximumSize(QtCore.QSize(400, 500))
        self.input_fields_frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(103, 19, 118);\n"
"border-radius: 20px; \n"
" }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.input_fields_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_fields_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_fields_frame.setObjectName("input_fields_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.input_fields_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.input_fields_frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_5.setStyleSheet("border:None;\n"
"border-radius: None; ")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btn_close = QtWidgets.QPushButton(self.frame_5)
        self.btn_close.setGeometry(QtCore.QRect(260, 0, 31, 31))
        self.btn_close.setStyleSheet("\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(30, 30))
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_5.addWidget(self.frame_5)
        self.profile_icon_frame = QtWidgets.QFrame(self.input_fields_frame)
        self.profile_icon_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.profile_icon_frame.setMaximumSize(QtCore.QSize(300, 300))
        self.profile_icon_frame.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"background-image: url(:/icons/icons/login_icon.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center;\n"
"border :solid  none\n"
"")
        self.profile_icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_icon_frame.setObjectName("profile_icon_frame")
        self.verticalLayout_5.addWidget(self.profile_icon_frame)
        self.frame_2 = QtWidgets.QFrame(self.input_fields_frame)
        self.frame_2.setStyleSheet("border:None;\n"
"border-radius: None;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.email_line = QtWidgets.QLineEdit(self.frame_2)
        self.email_line.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_line.setFont(font)
        self.email_line.setStyleSheet("padding-bottom:7px;\n"
"border:None;\n"
"background-color: rgba(0,0,0,0);\n"
"border-bottom: 2px solid rgba(46,82,101,200); \n"
"color:rgba(0,0,0,240);\n"
"")
        self.email_line.setAlignment(QtCore.Qt.AlignCenter)
        self.email_line.setObjectName("email_line")
        self.verticalLayout_3.addWidget(self.email_line)
        self.code_line = QtWidgets.QLineEdit(self.frame_2)
        self.code_line.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.code_line.setFont(font)
        self.code_line.setStyleSheet("padding-bottom:7px;\n"
"border:None;\n"
"background-color: rgba(0,0,0,0);\n"
"border-bottom: 2px solid rgba(46,82,101,200); \n"
"color:rgba(0,0,0,240);")
        self.code_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.code_line.setAlignment(QtCore.Qt.AlignCenter)
        self.code_line.setObjectName("code_line")
        self.verticalLayout_3.addWidget(self.code_line)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.input_fields_frame)
        self.frame.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_erorr = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.login_erorr.setFont(font)
        self.login_erorr.setStyleSheet("color: rgb(191, 0, 0);")
        self.login_erorr.setObjectName("login_erorr")
        self.verticalLayout.addWidget(self.login_erorr)
        self.btn_sencode = QtWidgets.QPushButton(self.frame)
        self.btn_sencode.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sencode.setFont(font)
        self.btn_sencode.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad,x1:0, y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120.219),stop:1 rgna(85,98,112,226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:15px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad,x1:0, y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,123,111.219),stop:1 rgna(85,81,84,226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.btn_sencode.setObjectName("btn_sencode")
        self.verticalLayout.addWidget(self.btn_sencode)
        self.verticalLayout_5.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.input_fields_frame)
        Forgot.setCentralWidget(self.centralwidget)

        self.retranslateUi(Forgot)
        QtCore.QMetaObject.connectSlotsByName(Forgot)

    def retranslateUi(self, Forgot):
        _translate = QtCore.QCoreApplication.translate
        Forgot.setWindowTitle(_translate("Forgot", "MainWindow"))
        self.email_line.setPlaceholderText(_translate("Forgot", "Email"))
        self.code_line.setPlaceholderText(_translate("Forgot", "Code"))
        self.login_erorr.setText(_translate("Forgot", "Code is not correct"))
        self.btn_sencode.setText(_translate("Forgot", "Send code"))
import traffic_rc
