# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_stream.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Stream(object):
    def setupUi(self, Stream):
        Stream.setObjectName("Stream")
        Stream.setWindowModality(QtCore.Qt.NonModal)
        Stream.resize(780, 900)
        Stream.setMinimumSize(QtCore.QSize(780, 900))
        Stream.setMaximumSize(QtCore.QSize(780, 900))
        Stream.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Stream.setLayoutDirection(QtCore.Qt.LeftToRight)
        Stream.setStyleSheet("background-color: rgb(71, 71, 106);\n"
"    \n"
"")
        Stream.setAnimated(True)
        Stream.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Stream)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_frame_draw = QtWidgets.QLabel(self.centralwidget)
        self.lbl_frame_draw.setGeometry(QtCore.QRect(40, 370, 700, 500))
        self.lbl_frame_draw.setMinimumSize(QtCore.QSize(700, 500))
        self.lbl_frame_draw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_frame_draw.setText("")
        self.lbl_frame_draw.setObjectName("lbl_frame_draw")
        self.frame_stream = QtWidgets.QFrame(self.centralwidget)
        self.frame_stream.setGeometry(QtCore.QRect(50, 70, 681, 241))
        self.frame_stream.setStyleSheet("QLineEdit{\n"
"    font: 13pt \"Times New Roman\";\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #000000;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    border-radius: 5px;\n"
"}")
        self.frame_stream.setObjectName("frame_stream")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_stream)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_stream)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_name = QtWidgets.QLineEdit(self.frame_stream)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_name.setFont(font)
        self.edit_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_name.setObjectName("edit_name")
        self.horizontalLayout_2.addWidget(self.edit_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_6.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_stream)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.edit_source = QtWidgets.QLineEdit(self.frame_stream)
        self.edit_source.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_source.setFont(font)
        self.edit_source.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_source.setObjectName("edit_source")
        self.horizontalLayout_6.addWidget(self.edit_source)
        self.btn_folder_stream = QtWidgets.QPushButton(self.frame_stream)
        self.btn_folder_stream.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_folder_stream.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_folder_stream.setStyleSheet("")
        self.btn_folder_stream.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_folder_stream.setIcon(icon)
        self.btn_folder_stream.setObjectName("btn_folder_stream")
        self.horizontalLayout_6.addWidget(self.btn_folder_stream)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(-1, -1, 10, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_stream)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_stream)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.edit_threshold = QtWidgets.QLineEdit(self.frame_stream)
        self.edit_threshold.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_threshold.setFont(font)
        self.edit_threshold.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_threshold.setObjectName("edit_threshold")
        self.gridLayout.addWidget(self.edit_threshold, 0, 2, 1, 1)
        self.edit_description = QtWidgets.QTextEdit(self.frame_stream)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.edit_description.setFont(font)
        self.edit_description.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_description.setObjectName("edit_description")
        self.gridLayout.addWidget(self.edit_description, 2, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame_btn_draw_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_btn_draw_2.setGeometry(QtCore.QRect(550, 330, 171, 31))
        self.frame_btn_draw_2.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(191, 191, 143);\n"
"    color: rgb(0,0,0);\n"
"    font: 14pt \"Times New Roman\";\n"
"    border: 2px solid  rgb(0,255,0);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #ffffff\n"
"}\n"
"")
        self.frame_btn_draw_2.setObjectName("frame_btn_draw_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_btn_draw_2)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_save = QtWidgets.QPushButton(self.frame_btn_draw_2)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_7.addWidget(self.btn_save)
        self.btn_reset = QtWidgets.QPushButton(self.frame_btn_draw_2)
        self.btn_reset.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_7.addWidget(self.btn_reset)
        self.frame_btn_draw = QtWidgets.QFrame(self.centralwidget)
        self.frame_btn_draw.setGeometry(QtCore.QRect(40, 330, 171, 31))
        self.frame_btn_draw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255,0,0);\n"
"    font: 14pt \"Times New Roman\";\n"
"    border: 2px solid  rgb(255,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #ffffff\n"
"}\n"
"")
        self.frame_btn_draw.setObjectName("frame_btn_draw")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_btn_draw)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_draw = QtWidgets.QPushButton(self.frame_btn_draw)
        self.btn_draw.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_draw.setObjectName("btn_draw")
        self.horizontalLayout.addWidget(self.btn_draw)
        self.btn_remove_draw = QtWidgets.QPushButton(self.frame_btn_draw)
        self.btn_remove_draw.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_remove_draw.setObjectName("btn_remove_draw")
        self.horizontalLayout.addWidget(self.btn_remove_draw)
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(740, 10, 31, 28))
        self.btn_close.setStyleSheet("QPushButton{border: None;}\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(98, 98, 147);\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(30, 30))
        self.btn_close.setObjectName("btn_close")
        Stream.setCentralWidget(self.centralwidget)

        self.retranslateUi(Stream)
        QtCore.QMetaObject.connectSlotsByName(Stream)

    def retranslateUi(self, Stream):
        _translate = QtCore.QCoreApplication.translate
        Stream.setWindowTitle(_translate("Stream", "Add stream"))
        self.label_2.setText(_translate("Stream", "Name"))
        self.label_6.setText(_translate("Stream", "Source"))
        self.label_3.setText(_translate("Stream", "Description"))
        self.label_4.setText(_translate("Stream", "Threshold"))
        self.btn_save.setText(_translate("Stream", "Save"))
        self.btn_reset.setText(_translate("Stream", "Reset"))
        self.btn_draw.setText(_translate("Stream", "Draw"))
        self.btn_remove_draw.setText(_translate("Stream", "Remove"))
import nike_app_rc
import traffic_rc
