# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(365, 585)
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.input_fields_frame = QtWidgets.QFrame(self.centralwidget)
        self.input_fields_frame.setGeometry(QtCore.QRect(10, 10, 321, 541))
        self.input_fields_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.input_fields_frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(103, 19, 118);\n"
"border-radius: 20px; \n"
" }\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.input_fields_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_fields_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_fields_frame.setObjectName("input_fields_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.input_fields_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.input_fields_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setStyleSheet("border:None;\n"
"border-radius: None; ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_close = QtWidgets.QPushButton(self.frame_3)
        self.btn_close.setGeometry(QtCore.QRect(260, 0, 31, 31))
        self.btn_close.setStyleSheet("\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(30, 30))
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.profile_icon_frame = QtWidgets.QFrame(self.input_fields_frame)
        self.profile_icon_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.profile_icon_frame.setMaximumSize(QtCore.QSize(300, 300))
        self.profile_icon_frame.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"background-image: url(:/icons/icons/login_icon.png);\n"
"background-repeat:no-repeat;\n"
"background-position: center;\n"
"border :solid  none\n"
"\n"
"\n"
" ")
        self.profile_icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_icon_frame.setObjectName("profile_icon_frame")
        self.verticalLayout_3.addWidget(self.profile_icon_frame)
        self.frame_2 = QtWidgets.QFrame(self.input_fields_frame)
        self.frame_2.setStyleSheet("\n"
"border:None;\n"
"border-radius: None;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.username_line = QtWidgets.QLineEdit(self.frame_2)
        self.username_line.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username_line.setFont(font)
        self.username_line.setStyleSheet("padding-bottom:7px;\n"
"border:None;\n"
"background-color: rgba(0,0,0,0);\n"
"border-bottom: 2px solid rgba(46,82,101,200); \n"
"color:rgba(0,0,0,240);\n"
"")
        self.username_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_line.setAlignment(QtCore.Qt.AlignCenter)
        self.username_line.setObjectName("username_line")
        self.verticalLayout_2.addWidget(self.username_line)
        self.email_line = QtWidgets.QLineEdit(self.frame_2)
        self.email_line.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_line.setFont(font)
        self.email_line.setStyleSheet("padding-bottom:7px;\n"
"border:None;\n"
"background-color: rgba(0,0,0,0);\n"
"border-bottom: 2px solid rgba(46,82,101,200); \n"
"color:rgba(0,0,0,240);")
        self.email_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.email_line.setAlignment(QtCore.Qt.AlignCenter)
        self.email_line.setObjectName("email_line")
        self.verticalLayout_2.addWidget(self.email_line)
        self.password_line = QtWidgets.QLineEdit(self.frame_2)
        self.password_line.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_line.setFont(font)
        self.password_line.setStyleSheet("padding-bottom:7px;\n"
"border:None;\n"
"background-color: rgba(0,0,0,0);\n"
"border-bottom: 2px solid rgba(46,82,101,200); \n"
"color:rgba(0,0,0,240);\n"
"")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line.setObjectName("password_line")
        self.verticalLayout_2.addWidget(self.password_line)
        self.repassword_line = QtWidgets.QLineEdit(self.frame_2)
        self.repassword_line.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.repassword_line.setFont(font)
        self.repassword_line.setStyleSheet("padding-bottom:7px;\n"
"border:None;\n"
"background-color: rgba(0,0,0,0);\n"
"border-bottom: 2px solid rgba(46,82,101,200); \n"
"color:rgba(0,0,0,240);\n"
"")
        self.repassword_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repassword_line.setAlignment(QtCore.Qt.AlignCenter)
        self.repassword_line.setObjectName("repassword_line")
        self.verticalLayout_2.addWidget(self.repassword_line)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rd_admin = QtWidgets.QRadioButton(self.frame_4)
        self.rd_admin.setObjectName("rd_admin")
        self.horizontalLayout.addWidget(self.rd_admin)
        self.rd_guesst = QtWidgets.QRadioButton(self.frame_4)
        self.rd_guesst.setObjectName("rd_guesst")
        self.horizontalLayout.addWidget(self.rd_guesst)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.input_fields_frame)
        self.frame.setStyleSheet("QFrame{\n"
"    border:none;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_erorr = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.login_erorr.setFont(font)
        self.login_erorr.setStyleSheet("color: rgb(191, 0, 0);")
        self.login_erorr.setObjectName("login_erorr")
        self.verticalLayout.addWidget(self.login_erorr)
        self.btn_register = QtWidgets.QPushButton(self.frame)
        self.btn_register.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad,x1:0, y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120.219),stop:1 rgna(85,98,112,226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:15px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad,x1:0, y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,123,111.219),stop:1 rgna(85,81,84,226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)
        self.verticalLayout_3.addWidget(self.frame)
        Register.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "MainWindow"))
        self.username_line.setPlaceholderText(_translate("Register", "Username"))
        self.email_line.setPlaceholderText(_translate("Register", "Email"))
        self.password_line.setPlaceholderText(_translate("Register", "Password"))
        self.repassword_line.setPlaceholderText(_translate("Register", "Re-Password"))
        self.rd_admin.setText(_translate("Register", "Admin"))
        self.rd_guesst.setText(_translate("Register", "User"))
        self.login_erorr.setText(_translate("Register", "Password is not correct"))
        self.btn_register.setText(_translate("Register", "Register"))
import nike_app_rc
import traffic_rc
