# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(400, 312)
        Setting.setStyleSheet("QWidget{background-color: rgb(134, 134, 134);}\n"
"QLabel{color: rgb(255, 255, 255);}")
        self.centralwidget = QtWidgets.QWidget(Setting)
        self.centralwidget.setObjectName("centralwidget")
        self.cmb_gridLayout = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_gridLayout.setGeometry(QtCore.QRect(200, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.cmb_gridLayout.setFont(font)
        self.cmb_gridLayout.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_gridLayout.setEditable(False)
        self.cmb_gridLayout.setObjectName("cmb_gridLayout")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.cmb_gridLayout.addItem("")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(360, 10, 31, 28))
        self.btn_close.setStyleSheet("QPushButton{border: None;}\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    \n"
"    background-color: rgb(177, 177, 177);\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(30, 30))
        self.btn_close.setObjectName("btn_close")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(140, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("background-color: rgb(91, 173, 121);")
        self.btn_register.setObjectName("btn_register")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(200, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(0.1)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        Setting.setCentralWidget(self.centralwidget)

        self.retranslateUi(Setting)
        self.cmb_gridLayout.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "MainWindow"))
        self.cmb_gridLayout.setItemText(0, _translate("Setting", "1 x 1"))
        self.cmb_gridLayout.setItemText(1, _translate("Setting", "2 x 2"))
        self.cmb_gridLayout.setItemText(2, _translate("Setting", "2 x 3"))
        self.cmb_gridLayout.setItemText(3, _translate("Setting", "3 x 3"))
        self.cmb_gridLayout.setItemText(4, _translate("Setting", "3 x 4"))
        self.cmb_gridLayout.setItemText(5, _translate("Setting", "4 x 4"))
        self.cmb_gridLayout.setItemText(6, _translate("Setting", "4 x 5"))
        self.cmb_gridLayout.setItemText(7, _translate("Setting", "5 x 5"))
        self.label.setText(_translate("Setting", "Display screen"))
        self.btn_register.setText(_translate("Setting", "Register"))
        self.label_2.setText(_translate("Setting", "Threshold"))
import traffic_rc
